services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_USE_FIREBASE_EMULATOR=true
      - VITE_FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - VITE_FIREBASE_FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
    depends_on:
      - firebase-emulator
    networks:
      - app-network

  firebase-emulator:
    image: node:18-alpine
    ports:
      - "4000:4000"  # Firebase Emulator Suite UI
      - "9099:9099"  # Auth Emulator
      - "8080:8080"  # Firestore Emulator
      - "5001:5001"  # Functions Emulator
      - "9000:9000"  # Hosting Emulator
    volumes:
      - .:/app
      - firebase_data:/app/.firebase
    working_dir: /app
    command: >
      sh -c "
        npm install -g firebase-tools &&
        firebase emulators:start --only auth,firestore,hosting --project demo-project
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  firebase_data: