services:
  # Build service for PWA
  build:
    image: node:22-alpine
    volumes:
      - ..:/app
    environment:
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    command: sh -c "yarn install --frozen-lockfile && yarn build"
    working_dir: /app
    profiles:
      - build

  # PWA testing service - serves built production files
  pwa:
    image: nginx:alpine
    ports:
      - "4173:80"
    volumes:
      - ../dist:/usr/share/nginx/html/SOTA
      - ./nginx.conf:/etc/nginx/nginx.conf
    profiles:
      - pwa